identity:
  name: Johan Edlund
  email: me@johanedlund.se
  website: https://johanedlund.se
  avatar: /avatar.webp
  tagline: I design and build for the world wide web from Malmö, Sweden.
  bio: Johan Edlund is a web designer living in Malmö, Sweden. He believes that Jesus Christ is the truth and the way.
  description: Personal site of Johan Edlund
  feedDescription: Jesus Christ is the truth and the way.
  address: |-
    Johan Edlund
    Västra Ryttmästaregatan 30D
    21752 Malmö
    Sweden
    Tel: +46706022495
profiles:
  github:
    url: https://github.com/pjedlund
    relMe: true
  mastodon:
    url: https://mastodon.social/@pjedlund
    relMe: true
    handle: '@pjedlund@mastodon.social'
  x:
    url: https://x.com/pjedlund
    relMe: false
  flickr:
    url: https://www.flickr.com/people/pjedlund
    relMe: false
  dribbble:
    url: https://dribbble.com/pjedlund
    relMe: false
  bluesky:
    url: https://bsky.app/profile/johanedlund.se
    relMe: true
  strava:
    url: https://www.strava.com/athletes/62084904
    relMe: false
repos:
  site: https://github.com/pjedlund/jedee
  licence: https://github.com/pjedlund/soli-deo-gloria-dedication
switches:
  breadcrumb: true
  nameReveal: true
  easteregg: true
  eastereggKeyword: jesus
  eastereggShape: ❤️
  viewRepo: true
  hideFeatured: true
  hideNav: true
  noindexSite: true
wiki:
  visibility: public
search:
  enabled: true
  only:
    activity:
      activityType: orienteering
  types:
    - article
    - note
    - reading
    - watching
    - jam
    - photo
    - recipe
    - event
    - audio
    - video
    - activity
    - searchable
